route:
  receiver: 'mail'
  repeat_interval: 4h
  group_by: [ alertname ]


receivers:
  - name: 'mail'
    email_configs:
      - smarthost: 'mailhog:1025'
        auth_username: ''
        auth_password: ""
        from: 'your_mail@gmail.com'
        to: 'some_mail@gmail.com'


   